### ISSUE TITLE
Stored wrong plan in table?

### ISSUE THREAD

**Issue by PizzaL** [postgrespro/sr_plan#1]
Hi, 
I'm trying to use this extension to log **query plan** ( the input para _Query *parse_). Please correct me if I understand it wrong. 

[At line 255 in sr_plan.c](https://github.com/postgrespro/sr_plan/blob/1ae6199f1c53e0a44038cb2a6876cdc61b1d745d/sr_plan.c#L255), it's actually storing the **execution plan** instead of **query plan**. 

Shouldn't log _parse_ instead of _pl_stmt_ at line 256?

**Comment by stalkerg** [comment]
> At line 255 in sr_plan.c, it's actually storing the execution plan instead of query plan.

yep, it's the main idea of this project - storing the whole execution plan. Also, we should make some hash for each "query" to find execution plan. 

I think the full name for this project will be Save and Restore - Execution Plan.

**Comment by PizzaL** [comment]
Thanks for the clarification. In that case, I guess https://github.com/PizzaL/sr_plan/blob/master/sr_plan.c#L176 should also use the _pl_stmt_ to generate the hash key then? Otherwise, there will be some mismatch?

**Comment by PizzaL** [comment]
ah, NVM, one is query_hash and another one is plan_hash.
